# Generated by Django 3.1.13 on 2022-05-25 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20220522_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Fecha_Ingreso',
            field=models.DateField(default=datetime.datetime(2022, 5, 25, 3, 24, 29, 189525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temp_inventario',
            name='Fecha_Ingreso',
            field=models.DateField(default=datetime.datetime(2022, 5, 25, 3, 24, 29, 189525, tzinfo=utc)),
        ),
    ]
