# Generated by Django 3.1.13 on 2023-08-13 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20220524_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Fecha_Ingreso',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 0, 25, 13, 298437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temp_inventario',
            name='Fecha_Ingreso',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 0, 25, 13, 300007, tzinfo=utc)),
        ),
    ]
