# Generated by Django 3.1.13 on 2022-05-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0002_auto_20211013_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones_ahorros',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datos_ahorros',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temp_datos_acciones_ahorro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temp_datos_ahorrante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
