# Generated by Django 3.1.13 on 2022-05-22 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20211013_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temp_caja',
            name='Fecha',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 23, 6, 31, 303398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temp_caja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
