# Generated by Django 3.1.13 on 2023-08-13 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_auto_20230812_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_caja',
            name='Fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 0, 26, 11, 134230, tzinfo=utc)),
        ),
    ]
